### ISSUE TITLE
Default Bindings for 3.0.0

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#102]
Default Bindings for 3.0.0 Are needed.

**At Minimum** we need to bind haptics, for wands and knuckles. I am indifferent on anything else.

- Possibly just upload a configuration we each like to workshop via steam accounts and leave it at that, besides the Haptics?

**Comment by username223** [comment]
It would probably make sense for us to make a "recommended" bindings config with features that are enabled in the overlay.

Complicated features (like @Kung-vr playspace stuff) should definitely have default bindings since it's very much not clear how everything works together. Stuff like the media keys should IMO be considered secondary, optional bindings. Especially considering how they don't have a toggle option.

**Comment by ykeara** [comment]
Perhaps we include Bindings similiar to what previously was in the version... i.e. room drag on menu button, leave others alone?


Also we need to remove the default HMD bindings that currently have Json's an artifact of when I was playing with proximity sensor will have to look at that in the future.

**Comment by Kung-vr** [comment]
Added in https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/pull/128
