### ISSUE TITLE
Playspace resets after motion on Oculus Rift

### ISSUE THREAD

**Issue by cubedparadox** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#133]
I've recently updated to v3.0.0, and am having some issues with the new motion options on Oculus.
I can configure bindings for dragging and turning without any problems, but when I release the button I'm dragging/turning with, I snap back to my original position prior to the motion.

Additionally, if I turn on gravity, I notice that my position doesn't reset until I hit the ground after throwing myself in the air, which leads me to believe it's not a problem with how I've configured my controller bindings.
When I press a motion button again, it snaps me back to where the motion left off, so the state isn't totally cleared by this bug.

I've confirmed this bug with a friend who also is using Oculus and has the same issues after updating. Nothing appears in my AdvancedSettings log file when this happens, and I've ensured there's no other SteamVR plugins installed while testing.

**Comment by ykeara** [comment]
Yea we have had some WMR users experience the same thing. Going to probably be a few days but we have a decent idea of what the issue is.

**Comment by ykeara** [comment]
Specifically on-going theory is that when we commit the chaperone from working copy that it may force people back to the start.... though should also be noted we have a WMR user who doesn't have the issue as well.

**Comment by Kung-vr** [comment]
Thanks for the report. The thing in common with landing and releasing binds is that I have it set to commit the working copy of the chaperone to disk whenever motion is halted. It seems that some setups are reverting rather than using the current working copy on commit. One way to partially confirm that this is the issue: I assume that even though your position is reset, you should still have some residual values in the offsets on the offsets-tab?

I will probably be building an option to disable this because working with an uncommitted chaperone should also mean that if advanced settings were to crash, the chaperone should revert to it's initial state. Which is a requested behavior. Once this is in, it should fix your issue. It may take a little time though because I did a full rewrite of chaperone handling for my motion updates, but other parts of the code touch chaperone and will trigger disk writes intermittently. So I need to rework all the remaining chaperone handling to collect the chaperone commits into just one place. (for example chaperone tab setups, floor fix, etc...)

In theory, it should be using the current working copy on commit and this shouldn't happen, so it may surface that there's another workaround because it only seems to affect some non-lighthouse users.

**Comment by cubedparadox** [comment]
@Kung-vr I can confirm that after using a motion button I have residual values in the offsets tab

**Comment by Kung-vr** [comment]
Thanks for the confirmation. I think this issue will be the next thing I'll be working on with the project.

**Comment by Kung-vr** [comment]
@cubedparadox It'll take awhile to consolidate all the chaperone commits in our code, but in the short term I have something for you to test that *might* fix things.

Could you [download](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23387574/job/x891t38ixkug1dbi/artifacts) and try this version? ( or if you want to build yourself it's [here.](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/tree/alpha-kung) )

The commit on motion halt also hides the working set preview (because we should then be synced with the commited copy) but this update forgoes hiding the working set. It's kind of a long shot, but it might fix things. ShowWorkingSetPreview() and HideWorkingSetPreview() are relatively new api calls in OpenVR and might be having unexpected behavior on non-lighthouse systems so it's worth a shot.

**Comment by cubedparadox** [comment]
@Kung-vr the version you linked seems to fix the problem, thanks!

**Comment by wickles** [comment]
Works for me too, thanks.

**Comment by ykeara** [comment]
3.0.1 is out now... should be a better fix... and fixes a few other issues as well.

**Comment by ykeara** [comment]
Should be Resolved now.

**Comment by cubiclestorm** [comment]
this issue is back after 3.10
