### ISSUE TITLE
[Request] Option to improve accessibility

### ISSUE THREAD

**Issue by Illuzio** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#135]
Hello, I play several games where my hands have to move a lot and very often I end up typing something because I can't see the real shape of my controllers. In games they are often replaced by something else: like hands, luminous orbs, electronic devices, pistol, etc... and it becomes very difficult to see if my controllers are close or not to my desk, my wall or my face. I have a very bad view and seeing the volume of the objects helps me a lot to find my way around, but with the games that change the controllers it becomes difficult to know where they are really in space, so that's my request:

Can you make an option that forces "normal controllers" to always appear in any game? (like those in SteamVRHome or with a transparency effect like that:
https://steamcommunity.com/sharedfiles/filedetails/?id=794843866
It would help me a lot in virtual reality!

I would also like to ask if it is possible to add an option to know if my controllers are very close to my headset/face to avoid collisions? (by making a grid appear around the face or with vibrations in the controllers if they are too close?)

And finally (promised it's the last request) an option to transform the click (pull the trigger) of the SteamVR Desktop into a double click!

Thank you very much and thank you for creating OpenVR !
(excuse my bad english, I'm french)

**Comment by ykeara** [comment]
okay first off.

show controller model.... maybe need to look into it... more or less it may make sense to do it if there is a reasonably easy implementation via api.

Chaperone for face/head - long story short.... you are going to have to really sell me on this one. why do we need it? doing an "okay" implementation  will either be way too permissive (i.e. trigger when controllers reasonably away from face. OR fairly tight (some headsets you could easily hit without "warning"

I don't really see  the use case.... and the proper solution would be non-trivial and require quite a bit of HMD/Controller specific code.... so the okay implementation is probably only one on table, and I don't think I could get a "good enough fit" tbh. soo why do you hit your head what games etc? what is the use case for other users?

3. almost certainly not.

**Comment by Illuzio** [comment]
Thank you for your answer, I understand that the implementation of its features is difficult or seems unnecessary, but for some people these settings can allow a much better comfort with the VR, being able to see its controllers all the time would already be a great improvement!

I'm going to answer your question about the grid around the head "why do we need it?" In my case, my problem is that I have very poor vision and I am systematically obliged to look at objects closely to see them clearly, even in Virtual Reality.

The HTC Vive or Oculus headset are not yet equipped with Dioptric lenses, which means that the vision in the helmet is identical to that of reality, so I have to wear my glasses and see badly what is far away in the games.

Here is some example where I have to bring my controllers closer to my eyes (these are also the situations where I often type in my helmet):
- The video broadcast on my right controller (option of SteamVR in order to see with the HTC Vive cameras)
- The objects and letters to be collected and read in Red Matter (or other puzzle games)
- The different electronic devices in my hands in Subnautica (and probably in the future game No Man's Sky)
- The texts that appear on my wrist in Lone Echo
- Or simply take and admire the objects up close

For these reasons, a system to know if my controllers are near my headset would be very useful!
(excuse my bad english)

**Comment by ykeara** [comment]
Okay I don't think we are going to do these at this point. Perhaps still force show the controllers. (as I am 90% sure its an api call).

I would highly recommend you getting a pair of lenses for your headset or wearing your glasses/contacts while In VR. Sorry I can't really offer better advice then that, but I wear my glasses myself, and will probably be buying prescription lenses for my index.

As the solution is non-trivial, and the target audience appears to be very small it just doesn't make sense to implement, I plan to be working on some code that would make it fairly trivial to implement, but for another feature.

And probably the biggest reason to not support it is the amount of specific cases for EACH headset we would have to do. It would require having and testing for each headset or the bounds couldn't be accurate enough, even then it would be limited use because I think at speed it would be worthless if you didn't want it to be obtrusive... i.e. when playing games like beatsaber my hands often go VERY near the HMD but just positional awareness and obviously not trying to bring things to my head prevents issues.


Closing Issue.
