### ISSUE TITLE
3.0.1 keep having to run room setup. chaperone proximity warnings no longer function

### ISSUE THREAD

**Issue by Kentypoo** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#148]
keep having to re-run room setup when starting vr. space turning breaks re-spawn point in a-lot of games.  this prolly isn't fixable.

**Comment by ykeara** [comment]
Okay.

As it stands now.

1. chaperone warnings are applied to the "live" set of chaperone data i.e. the file.... this means offsets will break this.

2. 3.0.0 and 3.0.1 BLOCK room setup from applying.
to Fix this go to "C:\Program Files (x86)\Steam\config" and delete "chaperone_info.vrchap" (this is your chaperone file.)

3. I would either back-up the .vrchap file OR use the chaperone profiles in game to save it for "easy re-apply"

4. This will break some seated games as they can't apply their seated position  either.

2.8.0 DOES NOT have these issues, We are aware of the issue and are trying to fix it.

So what is the issue: Essentially we are trying to use a "working" copy of the chaperone rather than the "live" copy..... this causes some issues, as the behavior is not identical across Vive/LH tracking and WMR/Rift systems.

So why did you change it? Theoretically we were writing to disk 90 times / second with 2.8.0 (in actuality its probably way less) and our goal is to minimize/eliminate those writes.

Also make sure you are on 3.0.1 there is some chaperone drift issues in 3.0.0 that we have already addressed related to this problem.

I don't have an eta other than soon. We know the issue, and are testing fixes/work-around every 24-36 hours or so...

**Comment by Kentypoo** [comment]
thanks for all the hard work. I love having these settings, when they work. love the manual re-directive walking in my garage.  smooth turn might be cool to have as well.

**Comment by Kung-vr** [comment]
Thanks for the report! Aware of the room setup failure to apply. I know why it's happening and should have a fix for that pretty soon. Until then you can use the workaround Ykeara posted. Seated mode is a little harder but working on that too. Once I get something working I'll post a link here if you'd like to test before it gets rolled into official release.

**Comment by Kung-vr** [comment]
Here's a [download for a build](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/23629783/job/1c8e83a3gx0vnby0/artifacts) that should fix application of chaperone from room setup. ( https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/commit/bb76ebf9853a4fd8a21874e1310001f5c425ede9 )

Seated position support is still a work in progress.

**Comment by ykeara** [comment]
Pr #150 addresses will open new issue for chaperone warnings
