### ISSUE TITLE
add scrollbar to desktop overlay for moving it horizontally

### ISSUE THREAD

**Issue by SupraLP** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#175]
add scrollbar to desktop overlay for moving it horizontally without going into advanced settings overlay. I have a triple monitor setup and for using it in vr i had to make it 3x as big... meaning the other monitors are far away to the sides. being able to move the whole desktop overlay on the fly would be really awesome.

**Comment by ykeara** [comment]
This is not possible w/ the valve overlay, and somewhat outside the scope of Adv-Settings.

WE are hooking into valve's overlay here and adjusting its position we can't directly change it.. i.e. no dynamic updates, no scroll bar.

In order to add a scroll bar we would essentially have to create our own desktop overlay (very do-able) just well outside the scope of ADV-Setttings.
