### ISSUE TITLE
Apply Space Settings Offsets as Center, does not adjust chaperone bounds.

### ISSUE THREAD

**Issue by neoaptt** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#192]
In offsets If i set x = 1 and z = 1 and y = 1. My chaperone moves with me on the X and Z access and i'm floating in the air of the Y access (or can go underground on the Y access). I can then reset my offsets and return back to the origin. When i set x and z and y = 1 then click "Apply Space Settings Offsets as Center". When i click return back to origin, will stay put. I can fix the floor by doing the "fix floor" option and laying one of my controllers on the ground. So it seems like everything is fixed and my offsets are zeroed out. But when i restart steam vr my chaperone has moved to the z = 1, and x = 1 position. But i'm left behind. Meaning that I have to run room setup again to get back my chaperone to the correct position.

I would like an option so that this issue can be avoided and I don't have to run room setup again. 

It would be cool to have 2 extra buttons. 1 that creates a snapshot of the current state of steam vr offsets and center. And another that returns to that snapshot. That way i can take a snapshot of the offset and center settings I'd like to have, and when i restart steam vr I can manually go back to that snapshot.

**Comment by ykeara** [comment]
yep that's a bug.... if you need to save your chaperone you can save it via chaperone tab and it will re-apply offset issue may persist but it will prevent you from re-running set-up in the mean time. (just re-apply the "good" set-up....


Yep had some issues with how we are handling some of the chaperone calls looks like we missed a case We are planning on doing some profiles for chaperone offsets as well as we had a revert feature that we disabled because of above issue.

**Comment by neoaptt** [comment]
any update on this 2 months later?

**Comment by neoaptt** [comment]
3 Months later?

**Comment by ykeara** [comment]
should be fixed with 4.0.0 and newer
