### ISSUE TITLE
Advanced settings Binds not appearing in Controller binding

### ISSUE THREAD

**Issue by lrh3370** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#206]
![image](https://user-images.githubusercontent.com/40906448/58376789-cad0cb00-7fb5-11e9-8c29-3e8e557b3fc4.png)
![image](https://user-images.githubusercontent.com/40906448/58376799-d6bc8d00-7fb5-11e9-9eaf-dc217812060c.png)
![image](https://user-images.githubusercontent.com/40906448/58376802-dd4b0480-7fb5-11e9-9de8-ca01d1ababa9.png)
The binds aren't appearing anywhere. I cannot bind motion controls to my controls.
I'm on steamVR beta 1.4.18

**Comment by TeraGX** [comment]
Possibly you're just in the wrong section, I certainly looked in the wrong place at first too. Don't go to the bindings section of a specific game, scroll all the way through until you find an entry specifically for Advanced Settings: 
![image](https://user-images.githubusercontent.com/8115542/58378121-624d0400-7f4b-11e9-99c5-250bfb24111d.png)
I'm guessing this is because it binds in an additive way, like it won't be responsible for deleting base bindings for a game. I hope that addresses your issue

**Comment by ykeara** [comment]
As Tera has said it is its own application in the binding interface,  it should be noted if you open it up on the desktop some resolutions cause it to get clipped so you won't really see it.

https://i.imgur.com/L7W7eEX.png as an example

Closing issue as it should be resolved, if its not just comment again and I can re-open it.
