### ISSUE TITLE
[feature request] Per-eye rotational render offset

### ISSUE THREAD

**Issue by lavenderaudio** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#207]
As described in detail [here](https://www.reddit.com/r/Vive/comments/5g5a3t/compensating_for_eye_angle_deviation/) the option to adjust the rotation per eye is a feature I've been hoping to come around for a while, acting similar to how prisms work on glasses to correct eyes back into stereoscopic vision.

Pretty much all the caveats are described in that linked thread, and I too am willing to cope with the adverse effects. I more want to have this feature as something experimental.

Obviously something like this should come with a warning to not mess with it too much as it could cause adverse eye strain or headaches, and a one tap reset button (Close one eye to line up the pointer), I would also argue for requiring to hit a Save button before exiting SteamVR else it will revert back to 0,0,0 on both eyes on next launch.

Hoping this can be added sometime in the future! Sorry if this is hard to understand, not really a programmer as such so GitHub is already quite confusing for me!

**Comment by ykeara** [comment]
I don't think this is actually possible.

my understanding of how the compositor magic works is it takes 1 image...... "splits it" (its more like both images are say 60% of original) to essentially make your viewpoint. so Actually adjusting the angle of 1 eye is impossible afaik.....

you can grab each eye's image.... and it might be possible to do magic w/ that to make it work but I am pretty sure it would be headset dependent.

At any rate it would probably need to be a driver rather than our program  to override the normal hmd you would use......

I will leave this  issue open for a bit to see if anyone else has any input or good ideas, but its not really technically feasible for this project I don't think.

**Comment by ykeara** [comment]
Closing out, now unless someone comes up with a good solution then can re-open... but this is a driver issue/physical hardware Issue I think.
