### ISSUE TITLE
Room rotation causes changes in X and Z coordinates

### ISSUE THREAD

**Issue by ragesaq** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#210]
I very, very frequently use OpenVR Advanced Settings to rotate my playspace and I've noticed that as of the 3.X branch when I do so it also changes the X and Z values. I then always have to set back to 0 to get my room space set the way I want.
I always only want to apply a rotation, and not have any other adjustments made.

**Comment by Kung-vr** [comment]
This is caused by the HMD centered rotation to support space-turn allowing redirected walking. Using space-turn without head centered rotation would cause you to orbit your room's center rather than turn in place. I wasn't sure if there was any demand for the old room orbiting style. Thanks for voicing the need. I'll put it on the list to add an option to disable the HMD centering. Just out of curiosity, what's your use case?

**Comment by ragesaq** [comment]
Mixed reality players use it to adjust the room angle to make for a good camera angle all the time. I would really like to not have to mess with X and Z coords every time to get rotation in place, especially if I need to make a few adjustments.

**Comment by Kung-vr** [comment]
@ragesaq If you'd like, you can use an early build that resolves this at [this link](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/25450456/job/qqsfifflav3csji2/artifacts). To activate the requested behavior open the settings tab and find and activate the new "Universe-Centered Rotation (Disables HMD Centering)" checkbox
