### ISSUE TITLE
[Feature Request] Allow cropping of Desktop Overlay to a single display

### ISSUE THREAD

**Issue by elvissteinjr** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#211]
I've left the tip on reddit in April as a guess, but now I got curious and confirmed it working with a crude test application.
You can crop the Desktop overlay via vr::VROverlay()->SetOverlayTextureBounds() just fine. Mouse interaction will behave as expected as well. By default the UV values are 0.0 for min and 1.0 for max, so the texture is always exactly the size of the desktops and not padded.

I'm suggesting to add settings to allow cropping to the size and position of a single display using this. It would improve the usability in multi-monitor environments greatly.

**Comment by username223** [comment]
Hey, sorry for the long wait, I've been pretty busy lately.

We'll look into implementing this, but it won't be a top priority right now.

The implementation will need to support at least Linux and Windows (Mac optional) and it will need some way of being controlled through the Advanced Settings overlay.

I noticed you've created a POC [here](https://github.com/elvissteinjr/SteamVR-PrimaryDesktopOverlay). If you want, I can send you a link to the developer Discord and you can look at implementing it yourself? It would definitely help out since we're all pretty busy at the moment and you'll be able to implement the feature to do exactly what you need it to do.

**Comment by elvissteinjr** [comment]
Thanks for the reply. For now I'll have to decline as well on implementing it myself, though.

As selfish as it may sound, that PoC satisfies my own needs perfectly well as is for now. That one was a quick and dirty write. Something worthy of integration into AdvancedSettings would likely take some time, especially since I have zero experience with Qt. I also some other private projects with other people involved.

So not right now. Perhaps in the future at some point. That's not to say I totally wouldn't mind if anyone else picked it up before that. At that point, I'd be able to support Linux myself. Qt likely also provides everything needed for this to not delve into platform-specific APIs. The Windows API use in my PoC was just for not pulling many dependencies and keeping the whole thing short.

I respect all the work you guys have done for this pretty much essential VR tool. For now I really just wanted to put the concept out there since it remained untouched while being pretty simple at its core.

**Comment by ykeara** [comment]
Going to close out With newest changes via valve looks like this is not going to be feasible.
