### ISSUE TITLE
[Request] Want to manipulate AdvancedSettings on Desktop

### ISSUE THREAD

**Issue by kenyken** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#218]
I'm using Oculus Rift and when I try to use Steam VR, all overlay applications like Open VR "Space Calibrator" and "Advanced Settings" won't show up the settings on the dashboard. I could just see the buttons of those overlay apps are added on the dashboard but those didn't work.
I believe there's something wrong with Steam VR. Now I can just use Space Calibrator in my environment because it has like-desktop mode, which the application shows up on desktop then I adjust the tracker without VR.
Do you have this setting like make possible to use Advanced Setting on desktop without VR? Or can you add this in the future?

sincerely

**Comment by ykeara** [comment]
In the install directory There is a "start desktop mode" batch file that should do just that...... though you may have to start SteamVR w/ that rather than just launching it via Steam or w/e..... that being said if the button is not showing up Try to manually start Advanced Settings while SteamVR is running (just run advancedsettings.exe from the install directory)

Another good way is to check the binding interface if it appears in the list it should be running/registered.

**Comment by kenyken** [comment]
Yes I could find the "start desktop mode" and that worked. I'd better to see the directory more carefully before asking... Anyway, I really appreciate your help!
