### ISSUE TITLE
Keyboard Input is bugged

### ISSUE THREAD

**Issue by fwenny** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#247]
New version Keyboard Input seems to be not working correctly.

Spaces and special characters (for example question marks) do not appear in whatever text field Im typing.

Works fine with older version.

**Comment by username223** [comment]
Are you talking about the `Keyboard Input` button in the `Utilities Page` or VR keyboards in text fields?

If it's the first then a guide to the new system can be found [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/keyboard_input_guide.md). 
TL;DR: is that spaces can be sent with `SPACE` (all caps) and question marks are not directly supported.

**Comment by fwenny** [comment]
huh? that makes no sense.
the keyboard was working fine, why change it and make a new system that has no direct buttons to press on?

**Comment by username223** [comment]
Because the system needed to be updated to support modifier keys (Ctrl, Shift, Alt, Super) and other platforms (Linux).

There are so many keyboard layouts that it's literally impossible to support all of them across both Windows and Linux.

Symbols not defined in the [spec](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/specs/Keyboard_Manager-Parser_Spec.md) are deliberately not supported because of the requirement that the parser should be simple to understand for end users and to maintain a relatively simple implementation.

Depending on your keyboard layout the question mark may be on the number keys, in that case you can send it by using the shift modifier `>` before that number key. So if the question mark was on key 0 you would write `>0`.

If the question mark is not on the number row you could write an AutoHotkey script that catches a key sequence and inserts a question mark.

**Comment by fwenny** [comment]
Okay, I understand. So for now Ill need to find alternative keyboards to use, or stick to older version of AdvancedSettings.
