### ISSUE TITLE
Add back in the Push-to-talk feature from 2.8.0

### ISSUE THREAD

**Issue by Rei1226** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#256]
Hi, I'm someone that still uses the 2.8.0 version of AdvancedSettings because after that is when the Push-To-Talk ability was changed from actually letting you declarate a push to talk button to just a message that says "Use steamVR bindings instead" basically.

I'm someone that plays VRChat, and I really like being able to use AdvancedSettings to set it so I push my thumbstick in to turn my mic on to talk. However, in the newer versions of AdvancedSettings, this is no longer allowed and it just tells you to use the SteamVR bindings for the game instead. While there is a mic toggle binding for VRChat in the SteamVR settings, it is bound for the application itself instead of SteamVR as a whole. This means I'd be using VRChat's mic toggle feature, which puts a giant glowing red circle on your HUD to indicate that your mic is muted which is extremely annoying and immersion breaking and something I'm able to avoid by using the AdvancedSettings push to talk feature instead. I'd like if this feature can be re-added to newer versions of AdvancedSettings going forward.

**Comment by username223** [comment]
The PTT feature is still in, you just need to select the key through the SteamVR bindings menu (for Advanced Settings).

Guide [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/SteamVRInputGuide.md). It's the exact same as keybinding a regular application, although you'll probably need to scroll all the way down to find Advanced Settings because of how SteamVR lists applications.

**Comment by ykeara** [comment]
Closing Issue as is resolved. If there is still another issue in regards to this re-open.
