### ISSUE TITLE
Chaperone settings will not allow me to change the chaperone height.  

### ISSUE THREAD

**Issue by arleas** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#264]
**Describe the bug**
From the Chaperone settings menu, you can change how bright the chaperone bounds are, how far away it fades into/out of view, and how tall it is.  For the height, it's stuck at 2.0 and would not let me change it.  If I changed it from 2.0 to any other value (higher OR lower) it would automatically jump back to the previous value. 

**To Reproduce**
1. click on Chaperone settings
2. try to adjust the chaperone height settings
3. notice that the height settings reset to the 2.0 value 

**Expected behavior**
I expected the height settings to stick with what I changed it to, not revert as if it was some hard-coded value.

**Screenshots**
I wish I had thought of screenshots but I ididn't take one and I've already uninstalled the program due to another issue. 

**Software (please complete the following information):**
 - OS: Windows 10 Pro 64Bit
 - Advanced Settings Version: 3.2

**Hardware (please complete the following information):**
 - CPU: Intel i7 4770K
 - Graphics Card: EVGA GTX 1080 Ti
 - HMD: Pimax 5K+

**Additional context**
somehow it seems like the settings persisted even after uninstalling the program and there are no controls from Steam's side of things that would allow me to fix it.

**Comment by Kung-vr** [comment]
This is because the slider was tracking with motion features. As the user drags vertically the height extends. Motion features are implemented such that we attempt to avoid per-frame disk writes and instead use what the openvr api calls the "working set preview" of the chaperone. If the slider were functional, while it tracked along it would force application of the chaperone to disk every frame. Anyway, this was temporarily disabled to solve that issue but that "temporary" fix was quite awhile ago. Thanks for the reminder, I should get on this. The solution is probably to add an apply button for the slider so it doesn't track and force application in real time.

**Comment by ykeara** [comment]
If you want to fix it re-running room-setup should work, or deleting / replacing `chaperone_info.vrchap` in `C:\Program Files (x86)\Steam\config` by default should also work as a fix.

**Comment by arleas** [comment]
Yeah I wound up having to do that anyway due to the "pitool" messing things
up on me.  Looking forward to the fixes in the future.
