### ISSUE TITLE
Advanced settings refusing to work (multi-gpu/related)

### ISSUE THREAD

**Issue by SmugOwl** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#324]
**Describe the bug**
Advanced settings refuses to start when i start up steam vr, even though i've set it to start with steam vr, and even though i launch it after steam vr launched, none of the things like offset works

**To Reproduce**
It happens constantly when launching steam vr, have done multiple fixes and fresh installs of it

**Expected behavior**
It should start with steam vr and all of the features should work but it doesn't

**Screenshots**

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: 4.0.1

**Hardware (please complete the following information):**
 - CPU: intel i7 8700
 - Graphics Card: GTX 1080
 - HMD: 

**Additional context**

**Comment by ykeara** [comment]
can you do a pastebin of the OVRAS log (%appdata%/AdvancedSettings-Team/AdvancedSettings.txt)
and the "vrserver" logs from valve (C:\Program Files (x86)\Steam\logs\vrserver.txt [by default])


also check and verify in C:\Program Files (x86)\Steam\config\appconfig.json that Advanced Settings is present.

I would also suggest uninstalling w/ uninstaller and then delete folder advanced settings, then try to re-install in a different location. via manual or w/ automated. In some configurations of windows permissions don't appear to play nice.

**Comment by SmugOwl** [comment]
Sadly the AdvancedSettings.log and vrserver.txt are over the maximum paste size that i have on pastebin, but i'll make some txt documents and send them here,, and in appconfig.json it says
{
   "manifest_paths" : [
      "C:\\Program Files (x86)\\Steam\\config\\steamapps.vrmanifest",
      "c:\\ProgramData\\HTC\\Vive\\ViveApps\\3a36561d-7706-474e-ad1c-f0d4656f10c3\\1543439764\\app.vrmanifest",
      "E:\\Playspace Mover\\OpenVR-AdvancedSettings\\manifest.vrmanifest"
   ]
}

[AdvancedSettings.log.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3866618/AdvancedSettings.log.txt)
[vrserver.txt](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/3866619/vrserver.txt)

**Comment by SmugOwl** [comment]
And i've done fresh installs of the advanced settings folder and its location before, hasn't worked

**Comment by Kung-vr** [comment]
As a troubleshooting step, could you try reinstalling steamvr then restart your computer and try again? Also if you delete/backup-and-move your log file it'll start a new smaller one.

**Comment by username223** [comment]
@SmugOwl 
Could you try running the `AdvancedSettings.exe` executable with a `--desktop-mode` flag, like `AdvancedSettings.exe --desktop-mode`?

**Comment by Drizzard2** [comment]
I have the same problem.

I have: Reinstalled revive. Reinstalled SteamVR. I am not running beta. Reinstalled Advanced Settings. Everything works but the menu won't open in VR. The button is there, makes the sound.

Opening with --desktop-mode works, opening the menu as normal on my desktop.

I have two graphics cards. My dual monitors are on graphics card 1, my VR is on graphics card 2. Both nvidia geforce 1080's. I have set the apps (revive and advanced settings) to force run on graphics card 2, same as my VR headset. Still doesn't work.

**Comment by Drizzard2** [comment]
Also, I have full admin rights on my account and have set all apps to run with admin rights.

**Comment by username223** [comment]
@Drizzard2 
I suspect that SteamVR works weirdly with more than one graphics card, could you try either with only one card or with all video outputs plugged into the same card?

Additionally, with the new 1.9.0 SteamVR, can you still see your desktop overlays inside VR?

**Comment by Drizzard2** [comment]
@username223 Everything works perfect with 1 graphics card.

When I have 2 graphics card, the desktop overlays, revive overlays and advance settings overlays refuse to work.

By defaulting to one graphics card with SLI, all my problems are solved.

Seems that SteamVR cannot handle multiple GPU's well.

**Comment by FordMustang0288** [comment]
I have the same problem and I have also tried to reinstall steamVR and Advanced Settings. 

Worth noting that I am trying to use an oculus quest. Steam VR thinks my starting position is 2 ft beyond the guardian. No buttons will bring up a position offset once I install Advanced Settings.

**Comment by username223** [comment]
@FordMustang0288 I don't have any experience with using a Quest.

Can you run room setup to normalize your starting position?

Can you see the Advanced Settings overlay in the SteamVR? What is the actual issue?

**Comment by FordMustang0288** [comment]
@username223 I have not been able to trigger room setup even with a fresh install of steam when used with the link cable.

The issue about my position being beyond the guardian is that I cannot play any games as I am not in the correct position. The advanced settings related part of that is I cannot see the overlay in steamVR to add a positional offset to bring myself back into the play area.

I'll have to try the desktop flag later and see if that helps. If I try to rerun the advanced settings executable (since I'm not seeing anything) it says it is already running.

I'll also have to dig around more to try and see if I can trigger the room setup.

Thanks!

**Comment by ykeara** [comment]
@FordMustang0288  so oculus uses it's own "guardian" rather than steamVR's "chaperone"

also you will need to make sure you are running an app that is using SteamVR not the Oculus SDK

But assuming those are true are you in the "right" position if OVRAS is un-installed?

Assuming you can see Steam Dashboard is the Advanced SEttings icon there?

And if icon exists when clicking it what is the result a blank screen?

**Comment by FordMustang0288** [comment]
@ykeara
That makes sense that I would be using guardian vs chaperone. Do keep in mind I am running via the link cable with a game launched from viveport Infinity that runs steamVR, not Oculus.
What I mean about default play position, is when steamVR loads (you get into the grid based loading environment) I see a gray square outside of my play boundary which indicates that it senses the default position there. 
The viveport game will then be out of whack as my position is not where it was intending me to be.
If I launch steamVR from the Oculus library, I again see the same grid environment with a bad player position. Once I end up in the steamVR room/lobby I can open up the dashboard and get into the steamVR settings.
While in settings, I do not see advanced settings this I cannot click it. I've also tried pressing all buttons on the controllers to maybe launch something but nothing comes up other than the default steamVR settings. 

If I uninstall open VR, the default position is also bad...in the same way as described above. That is why I started trying to get open VR to work (because I read I could tweak the position offsets). 

Thank you

**Comment by FalconFour** [comment]
I've had an unbelievably, infuriating time trying to get "Advanced Settings" to open and run on any VR system I set up. The button occasionally shows up, but when trying to activate it, just a blank screen greets me. Absolutely nothing on the page.

Same with my most recent attempt. The Advanced Settings button is there in the system menu, but activating it just gives me a big expanse of NOTHING, with "Advanced Settings" written across the top.

This is with the newest hot version 4.0.1, with the SteamVR beta and without the beta, with my nVidia graphics enabled or disabled. Nothing can make it work. AND ALL I WANT IS JUST TO ROTATE MY VIEW 90 DEGREES. That's all I want. Room Setup can't proceed past checking for the headset, because even though VR is alive and active and tracking, it thinks the headset and controllers are both "Off". So I keep bashing my head against this god awful system...

And it's a wonder VR never really took off! Damn buggy ass pieces of garbage software...

**Comment by Kung-vr** [comment]
> with my nVidia graphics enabled or disabled

If you have multiple graphics adapters, there's an issue with overlays in steamvr where sometimes it doesn't render in the dashboard.

[See "Common Issues" in our readme](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#common-issues)

![image](https://user-images.githubusercontent.com/38249782/76163519-2b6a7680-618a-11ea-8ad5-a7d4622f3493.png)

**Comment by ykeara** [comment]
Edited title a bit to clarify, closing out issue, as issues appear to be resolved, no further responses. As well as to keep future issues isolated on one issue/ticket.
