### ISSUE TITLE
Is there any way I can save my chaperone bounds, because I spent a long time making one in ChaperoneTweak but as soon as I restarted SteamVR, it went back to what it was before

### ISSUE THREAD

**Issue by MaxAbillion12** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#327]

**Comment by Kung-vr** [comment]
If you want to run another app that modifies the chaperone along side Advanced Settings, you must have the option: "Allow External App Chaperone Edits (Danger)" enabled. It's in the Settings tab of Advanced Settings. Note that this feature will only work when you start from zero offsets.

If you want to make extra sure Advanced Settings picks up your edits, and save a profile of it, this should work:

1. Reset offsets in Advanced Settings
2. Turn on "Allow External App Chaperone Edits (Danger)" in the Settings tab
3. Make your edits in ChaperoneTweak
4. Go to the Offsets tab and click the [ + ] button next to X-axis (y or z would have worked too). This will grab the edited chaperone into Advanced Setting's cached copy that's used for motion features
5. Still in Offsets tab click Reset
6. in Chaperone tab create a new profile. In the new profile popup dialog check all the boxes to be sure you save all the details of the current chaperone setup.
7. It's now safe to disable "Allow External App Chaperone Edits" in the Settings tab.

Repeat that process every time you want to make a new tweak on the chaperone.

Side note: It's a little hard to get Advanced Settings to let go of its control of the chaperone bounds because when users do things like Space Drag, Advanced Settings must precisely cancel the resulting offset to the chaperone bounds to keep them in alignment. Anything else that messes with the chaperone at the same time runs the risk of misaligning the chaperone.

**Comment by ykeara** [comment]
Closing issue because resolved/explained.
