### ISSUE TITLE
Controller angle offset 

### ISSUE THREAD

**Issue by SuperV1234** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#335]
Older VR games that do not have native support for some controller types (e.g. Knuckles) can be unplayable due to the default mapping between the controller angle and the in-game hand angle ([example image](https://i.redd.it/7f4tdcurbo241.png)). 

Furthermore, even games with full support for a particular controller might have slightly different default angles, preventing muscle memory from building when - for example - shooting guns in VR. Consider switching between games such as Pavlov, Onward, and Arizona Sunshine - even a few degrees of difference can throw off a player's aim, leading to frustration. 

What I propose is the addition of a **"controller angle offset" setting**, which can be tweaked in the menu. This offset would be applied to the game's default angle. Players should be able to save and load profiles, and bind profiles to certain games. This will allow older VR games to be usable with "unsupported" controllers, and will also allow consistency between different games. Mockup:

![angleoffset](https://user-images.githubusercontent.com/918661/70252967-31f7e500-177a-11ea-9dde-31ee0d0e8e9b.PNG)

I believe this is as important as a FOV slider or mouse sensitivity slider for non-PC games. I am an experienced C++ developer and would love to contribute this feature, but I have zero experience with OpenVR and I'm not even sure this is possible. 

I am however sure that this is desperately needed :)

**Comment by username223** [comment]
Thank you for the issue.

I believe that this is an important feature that ideally would be a part of SteamVR directly, however for us to implement this would be a massive pain to maintain, would constantly break and would be outside the scope of this project.

I believe that [OpenVR-InputEmulator](https://github.com/matzman666/OpenVR-InputEmulator) provided this functionality, although I have no experience with that project.

You should probably open an issue on Valve's OpenVR repo or the steam message boards for this.

Closed as `wontfix` due to being outside of project scope.
