### ISSUE TITLE
Unable to do keybindings. SteamVR claims Advanced Settings is "Legacy"

### ISSUE THREAD

**Issue by Searaphim** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#338]
Title. I use the Index Knuckles and when I go to edit keybindings on Advanced Settings I only get two tabs: Legacy Bindings (Handed) and Setup Legacy Actions

And of course if I try to bind an action to one of the buttons, well, I will have none of the actions Advanced Settings should be giving me like Snap turn or Space grab...

**Comment by ykeara** [comment]
Make sure you are 4.0.1

Either you are pre 3.0 or its some initialization failure from the sounds of it.

First and foremost I would try re-install OVRAS, perhaps even SteamVR if its not too much hassle, but need Logs for Advanced Settings
%appdata%\AdvancedSettings-Team\AdvancedSettings.txt
And also probably your vrserver.txt from your steam install logs directory.

**Comment by Searaphim** [comment]
It seems to have fixed itself by opting in Steam Beta... I am really using 4.01 though. Seems like they made some seperation between the "Old binding UI" and the new one. Dunno if that's related in some way.

**Comment by Searaphim** [comment]
Here's the log https://mega.nz/#!PFsg2YwB!o9p_sfdFxX1Ohd3WCpG535M6P26t4xcOPDXHYBQfpyw

**Comment by Searaphim** [comment]
Quick update. It still works after reverting back to the non-beta branch. But now it's stuff like OVRToolkit that won't work...

**Comment by ykeara** [comment]
Due to the more major changes recently we can't really support the beta branch.

That being said I switched over and tested and didn't have any issues, glancing at the bug reports for SteamVR there may be a few related issues, and based on some of the changes they appear to be making It might be possible that there are some issues.

Looking at my logs locally, Its best to wait for changes to get pushed to live before addressing them.

As 1.9.x should be released very soon going to put this issue on hold until can look at it from what they changed.

**Comment by ykeara** [comment]
Still Having this Issue?

**Comment by ykeara** [comment]
Closing out issue, as no response, and presumably resolved.
