### ISSUE TITLE
Segfault after upgrade from Qt 5.13.2-3 to 5.14.0-1 on Arch Linux.

### ISSUE THREAD

**Issue by duckbytes** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#343]
**Describe the bug**
Running in a terminal, the output ends with:
`[INFO] 2019-12-24 13:43:26: Command line arguments processed.
[INFO] 2019-12-24 13:43:26: OpenVR initialized successfully.
[INFO] 2019-12-24 13:43:26: VR Runtime Path: /home/theo/.local/share/Steam/steamapps/common/SteamVR
[ERROR] 2019-12-24 13:43:26: Could not get recording override setting: VRSettingsError_UnsetSettingHasNoDefault
[ERROR] 2019-12-24 13:43:26: Could not get playback override setting: VRSettingsError_UnsetSettingHasNoDefault
[ERROR] 2019-12-24 13:43:26: Could not create brightness overlay: VROverlayError_KeyInUse
[ERROR] 2019-12-24 13:43:26: Could not create color overlay: VROverlayError_KeyInUse
[INFO] 2019-12-24 13:43:26: OPENSSL VERSION: OpenSSL 1.1.1d  10 Sep 2019
[INFO] 2019-12-24 13:43:26: Version Check: Recieved Data: { "major": 4, "minor": 0, "patch": 1, "updateMessage": "", "optionalMessage": "" }
[INFO] 2019-12-24 13:43:26: Version Check: Installed version is latest release.
[1]    58233 segmentation fault (core dumped)  /opt/OpenVR-AdvancedSettings/AdvancedSettings/AdvancedSettings
`

**To Reproduce**
- Start SteamVR
- run /opt/OpenVR-AdvancedSettings/AdvancedSettings/AdvancedSettings in a terminal

**Expected behavior**
Advanced settings should run in the background and be useable from SteamVR.

**Software (please complete the following information):**
 - OS: Arch Linux
 - Advanced Settings Version: git master

**Hardware (please complete the following information):**
 - CPU: i5 3570k
 - Graphics Card: AMD 5700XT
 - HMD: Vive

**Additional context**
Segfault seems to happen on line 54 in utils/setup.h for the notify override after running `return mainEventLoop.exec();` in main.cpp. It tries to pass receiver and event to `QApplication::notify`, but receiver has no value. Event is type 43: MetaCall. Other events work fine before this occurs.

While removing the override it still seems to segfault.

This commit to qtbase is the only maybe related difference I can see between the different versions:

https://github.com/qt/qtbase/commit/a1e62e7ba14b00ac7c361936a18e7bc42bf1286d#diff-16b3605b3ffc53d1736ba4221a032b62

where `Q_DECL_NOEXCEPT` is replaced with `noexcept`. Commit message is "In preparation of Qt6 move away from pre-C++11 macros."

Not sure if it's related to the comment in utils/setup.h lines 38 to 49.

qtcreator screenshot showing the segfault:

![Screenshot from 2019-12-24 13-46-35](https://user-images.githubusercontent.com/32309223/71415640-98bf3e80-2654-11ea-971f-e4b4c8cf9c71.png)

I haven't tested this on any other platforms.

Thanks!

**Comment by duckbytes** [comment]
Just installed Qt 5.12.6 as a kit and compiled it against that. It's working again.

Definitely seems like the new Qt release is the cause.

I can start using it again now at least!

**Comment by username223** [comment]
Excellent issue.

I don't have a lot of time right now but I'll look into this when I get some.

Thank you for the issue.

**Comment by username223** [comment]
@duckbytes If you have time could you paste the build log when using Qt 5.14.0 here?

**Comment by duckbytes** [comment]
Build log - https://gist.github.com/duckbytes/9a47ad498d7c07e5a7f4c02a9db82505

**Comment by username223** [comment]
@duckbytes Thank you.

When I tried building with 5.14.0 on Windows it did not copy the necessary files via the `COPIES` qmake variable. I thought that the SEGFAULT was a result of a file not being found. It seems like the files are being copied successfully on Linux.

You seem like a skilled Linux user. 
Could you load up the core dump in `gdb` and give a log of the `where full`, `disassemble`, `info locals`, `info args` and `info threads` commands (everything in one file is fine)?

Additionally, could you try running the executable from the build directory instead of the `make install` directory and report results?

**Comment by username223** [comment]
@duckbytes This issue will be fixed on `master` when PR #351 gets merged and will be in the next release (4.1.0).

OpenVR Advanced Settings v4.0.1 is also now on the [AUR](https://aur.archlinux.org/packages/ovras/), with the fix applied.

Thank you for creating this issue. The information you posted was very helpful, especially the comment about a downgraded Qt working, in narrowing down what was going on.

Please feel free to open issues another time. Nobody on the dev team runs Linux, so we don't know something doesn't work unless people tell us.

____

Problem in the end turned out to be a "use-after-free" in our code that did not segfault before Qt 5.14.0 for unknown reasons. [Solving commit here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/pull/351/commits/da5ff278aa6f409c5c5e4cfcaeee10514d093df4).

**Comment by duckbytes** [comment]
Awesome, thank you @username223. Happy to help. Sorry I didn't come back with those gdb logs you had requested.

Thanks for making an AUR version too.
