### ISSUE TITLE
Custom Keys - Mumble PTT

### ISSUE THREAD

**Issue by Mjolkspam** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#361]
To be fair, this is not an bug report, more an question. Don't know where to ask otherwise.

The three custom keys you can use and set to pretty much w/e keyboard key you want..
How, and is it possible to use Custom Key 1 on an Vive controller? Maybe on the grip buttons. 

I would like to have Right grip button to trigger CAPS, which is my Mumble PTT. I want this cause I'm no fan of voice activation.

Thanks for answers. And if this is not ok, as it's not an bug report.. I'm sorry :)

**Comment by username223** [comment]
You would go into your settings file in `%appdata%\AdvancedSettings-Team` on Windows and `~/.config/AdvancedSettings-Team/` on Linux and change `keyboardOne=^>m` to `keyboardOne=CAPS`. Then bind the keyboardOne action in SteamVR to grip.

Notice that it is not possible to hold a button down, due to technical limitations. When you activate the action (with grip), a button down event is sent and then immediately afterwards a button up event is sent.

To make this work, you would need to bind the toggle mute for use in VR.


You could also use the Push to Talk feature, which mutes and unmutes the microphone directly in Windows/Linux. This supports holding and releasing instead of just toggling.

Documentation for keyboard keys [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/keyboard_input_guide.md) and specification (including list of keys available) [here](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/specs/Keyboard_Manager-Parser_Spec.md).

**Comment by Mjolkspam** [comment]
The Caps part i managed to figure out. But I can't find or manage to bind keyboardOne action in SteamVR binding settings?
Open SteamVR, then I go into Settings > Controllers, then navigate myself to controller bindings.
I get a long list of things when I choose grip, but nothing with ovras / keyboardOne action.

**Comment by username223** [comment]
keyboardOne should be under the Misc category, in the top-center.

Can you bind it to other types of button, like the trigger or menu button?

**Comment by Mjolkspam** [comment]
Is this the place to bind?  I went through the SteamVR settings. I'm so confused about this. I'm rather new to VR and all this extra stuff.
![image](https://user-images.githubusercontent.com/7254570/74112322-f293ad80-4b9b-11ea-9319-bdb8f292e083.png)

**Comment by ykeara** [comment]
@Mjolkspam yes, but you are in the game for Beat Saber not advanced Settings.

The easiest way to get to Advanced Settings page is to simply click the "bindings" tab on the left side of the main page of advanced settings it should take you straight to this page in VR. (except for advanced Settings) 

or you can hit back a few times to get back to application select then select adv-settings and move forward from there.


 and can take a look at a guide to help you out maybe. (the link for desktop version might be busted as valve is messing around w/ UI etc.)
[steamvr input guide](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/docs/SteamVRInputGuide.md)

**Comment by ykeara** [comment]
Closing out issue as resolved/no-response.
