### ISSUE TITLE
Rotation adjustments not committing in all universes for WMR.

### ISSUE THREAD

**Issue by Eglin** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#363]
I'm not sure why it is so, but Steam insists on orienting my playspace towards my monitor.  I have gone through the room setup many times, but it's always the same (maybe my WMR room setup is overwriting?).  I have rotated it and tuned it with the advanced settings dialogue, but I don't really understand how to make it stick.  When I manually select the appropriate profile, it might be reset three times in the course of launching a single game.  I'd like it to be the default.  Orientation does matter, as the headset cable routes more comfortably in one particular direction.

Also, somewhat related issue... I can't seem to make the chaperone border disappear.  I can hide or show the SteamVR boundary and the center square, but I can't seem to affect the outer boundary (I presume imported from WMR).  It doesn't respond to the visibility settings or anything.  

Please help!

**Comment by ykeara** [comment]
So It's important to note that when using a non-native SteamVR headset the chaperone is actually provided by that program.

i.e. the WMR chaperone is set-up that way, and WMR prefers to face towards monitor, you can fake this by facing AWAY from your monitor during WMR set-up.


You can disable WMR chaperone's as an option in the WMR portal as well (should be the white lines).


As for the profile issue saving/loading can you explain your intended results, procedure, and what exactly happens better, That does sound like possibly a bug w/ our profiles.

**Comment by Eglin** [comment]
Thank you so very much for the patient explanation.  You were right about the border and I should've realized it was part of WMR, but it was the same teal color as Steam's chaperone and I didn't make the connection.  I will try to pick a fixed point on a wall or something to focus on while pacing out my perimeter next time I setup WMR.   I'm pretty sure the WMR chaperone is being affected by the rotations I'm applying with the OpenVR Advanced Settings app, which also confused me.

The procedure I've been using is to start SteamVR, click advanced settings, click chaperone, select my saved profile from the drop-down.  This resets the orientation to my liking.  Some games leave it as is.  Others are resetting it back to facing the monitor constantly.   Gun Club via Viveport works fine, for example, but Asgard's Wrath via Revive is _constantly_ resetting my orientation to face the monitor.

Another thing that confuses me is that most of the sliders on the chaperone page seem to have no impact on anything.  I don't seem able to change visibility or height or anything.  The distance one might work w/ the Steam area marker and the walls that spawn when you get too close to the border, but I can't see any way to make the small square a little less visible or change its height.  In the normal Steam settings, my chaperone level is set to novice or whatever the least permissive option is.  Could that be why I'm having trouble configuring things?

And at the risk of conflating one issue with another, might I trouble you for an explanation of how to switch between the sitting and standing 'universes'?  Should the software be recognizing when I sit immediately, or does it only determined at the time I launch a game, or what?  Is whether I need to adjust my height using your tool dependent on how the game handles things, or is there a generally consistent way to more seamlessly make adjustments according to whether you're in the sitting or standing "universe"?

**Comment by ykeara** [comment]
so The rotations of the world/chaperone should apply, but settings like height, fade-distance... etc. won't as technically you are using WMR's chaperone, now I do think you can Use Steam's chaperone w/ WMR by manually running the room setup executable from steam's files..... and if you turn your bounds off w/ WMR all settings should work (if you are using steam's chaperone)....

Note I am not 100% sure about it, it's been a bit since I have used my WMR and can't speak w/ 100% certainty.

The level of the chaperone should have no effect.... i.e. novice advanced etc. should have no issues.

As for the rotation not taking, that is probably a bug, and I will need to look if its addressable or not.

As for why it's happening in some games or others its probably a sitting/standing issue, as the behavior is different for each of those methods.

Also should note you can't really change the mode from sitting/standing etc. It's somewhat determined by how you set-up VR and the game itself can change it, but its not really a user setting.

One thing you can try is to launch SteamVR w/ WMR bounds on and then turn the bounds off via WMR portal AFTER you are in SteamVR.


Also going to adjust title to better reflect percieved bug

**Comment by pupphelper** [comment]
Is there any way to use OVRAS to force the steam chaperone on for WMR?  I know WMR somehow disables the wall because it has its own wall, but its really hard to see in game, and I want the full steamvr grid to make sure i don't hit anything.   If I disable WMR boundary, and enable everything OVRAS settings, it all works except the visual wall.  ie. if I toggle audio alarm or vibration in OVARS settings it works, just doesn't visually show the wall.

**Comment by ykeara** [comment]
@pupphelper in the future its best to make a new issue for something like this.... There is something I can and want to try stay tuned in discord I might do it very very soon (its relatively simple to implement)

**Comment by pupphelper** [comment]
@Eglin did you try to add the following to your steamvr.settings
   "driver_Holographic" : {
      "headsetReorientationDisabled" : "true"
   },

**Comment by Eglin** [comment]
Thank you so very trying to help me!  I'm sorry for being slow to respond.  I haven't revisited the game since my last post, and it may take me some time to get back to it now.  However, I did check the file and there was no such setting listed.  I will add it and try to get back to the game as soon as time allows!  Thanks, again, for trying to help.

**Comment by Eglin** [comment]
Thank you so very trying to help me!  I'm sorry for being slow to respond.  I haven't revisited the game since my last post, and it may take me some time to get back to it now.  However, I did check the file and there was no such setting listed.  I will add it and try to get back to the game as soon as time allows!  Thanks, again, for trying to help.

edit: My issue has the rotation off by 180 degrees, and not 90.  Is this change likely to help?

**Comment by ykeara** [comment]
@eglin any update, issue resolved etc? closing in 7 days if no response

**Comment by Eglin** [comment]
Unfortunately, I haven't been able to make time to get back into VR very much lately aside from an hour or so to putter around in Alyx since it released.  I have never had a good experience with chaperones/markers and their adjustment using a WMR headset with SteamVR, but it could easily be my fault for not spending hours poring over the configurations.  I just don't have sufficient time or interest.

Thanks for taking the time to look after my issues and to help me get it working.  And for the wonderful tools you're providing the community.
