### ISSUE TITLE
Better Keyboard Positioning.

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#383]
Unknown if Valve's keyboard issue w/ new overlay is oversight or intentional.

If intentional, and we don't implement our own keyboard. We need to better calculate keyboard position.

Currently we just grab the default overlay, and move it down, we need to rotate it up, and move it "towards" the player

**Comment by elvissteinjr** [comment]
For dashboard overlays, to achieve keyboard positioning like Steam's desktop, it just requires a call to VROverlay()->SetKeyboardPositionForOverlay(). The avoidRect passed to it seems to be ignored for dashboard overlays now so that doesn't matter.
The other keyboard positioning code could be removed then.
