### ISSUE TITLE
Documentation Standard

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#41]
[qt documentation system](http://doc.qt.io/qt-5/01-qdoc-manual.html) , is QT's doc system It is fairly easy to use,  and can be used across both QT and c++.

Hopefully can do a pass for 3.0.0 release

If there is a different system that would be more preferable I don't have any preference, and was doing my own thing.

Alternatively we can use a more standard c++ system

```
/**
    Explanation of function

    @param
    @return
    @other flags
*/
```

The former is a little more in depth, and produces professional documentation, but is another step to generate. The latter is quicker, but not quite as professional especially for what amounts to a production product.

Any opinion or other system suggestions are welcome.

**Comment by username223** [comment]
I would primarily want user facing docs, e.g. IDE tooltips and implementation details that might not be apparent.

Exporting to HTML using Doxygen or QDoc would IMO be a waste of time, since we're not a library that needs to enable third party users.

Visual Studio shows any comment (`//` or `/* */`) above the function as a function tooltip. Qt Creator only shows multi line comments formatted with an exclamation point, as `/*! */`.

Visual Studio does not format QDoc markup, while Qt Creator does.

Because we don't need HTML docs and Visual Studio just displays the comment raw, we should avoid using markup tags in comments.

We also need to ensure that comments are actually kept up to date, which means lowering the work needed to keep them updated. For this reason I don't believe we should mirror the function declaration in the actual comments. Especially since they aren't checked for correctness at compile time.

I think the documentation format should be as follows:

```cpp
/*!
Multiline comment and bang in order to enable Qt Creator tooltips. Brief function/enum/class description here.

Empty newline. After this Qt Creator will not include it in the tooltip. VS2017 will strip any newlines and include it.
Implementation specific things after the empty newline, to encapsulate as much as possible. 
VS2017 will also include single line comments below this, so we might as well keep everything inside the same comment block.
*/
void functionDefinition(const int param1, const bool param2) {
    [...]
    // Single line comments for implementation specific internal comments.
}
```

This allows us to have IDE tooltips and usable comments with very little overhead (since you were going to write comments anyway, right? ;-) ).


On a real function:
```cpp
/*!
Returns an INPUT struct with the corresponding virtualKeyCode and keyStatus set.

All fields except ki.wVk and ki.dwFlags are zero.
Function is noexcept because it only operates on built-in types.
The INPUT struct is used with the SendInput Windows function.
Official Docs:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-taginput
*/
INPUT createInputStruct( const WORD virtualKeyCode,
                         const KeyStatus keyStatus ) noexcept
{
    // Zero init to ensure random data doesn't muck something up.
    INPUT input = {};

    input.type = INPUT_KEYBOARD;

    input.ki.wVk = virtualKeyCode;

    if ( keyStatus == KeyStatus::Up )
    {
        input.ki.dwFlags = KEYEVENTF_KEYUP;
    }
    else if ( keyStatus == KeyStatus::Down )
    {
        // Struct is already zero initialized, but this is here for clarity.
        // Compiler will likely sort this out, otherwise the performance hit is
        // negligible.
        // There is no corresponding KEYDOWN event, you just don't
        // set KEYEVENTF_KEYUP.
        input.ki.dwFlags = 0;
    }

    // The sizeof(INPUT) on MSVC is 28. Returning by value is a non-issue
    // compared to the simplicity of not having to pass a ref to an already
    // existing INPUT struct, and possibly forgetting to zero it out.
    return input;
}
```

Will show this on Qt Creator:
![qt_creator_tooltip](https://user-images.githubusercontent.com/12849493/51073966-8b45ba00-1678-11e9-8779-0198b3bcbd23.png)

And this on VS2017:
![vs_2017_tooltip](https://user-images.githubusercontent.com/12849493/51073963-854fd900-1678-11e9-8154-66e6dfe7ba83.png)


Note: Qt Creator will insert asterisks in multi line comments unless it has been disabled in Tools->Options->Text Editor->Documentation Comments->Add Leading Asterisks. The other options under Documentation Comments will auto fill in Doxygen specific things. Recommend off  for our purposes.

**Comment by ykeara** [comment]
Probably  for the best since so many things are in limbo.

**Comment by ykeara** [comment]
I think that we are moving forward with more informal documentation as such closing issue.
