### ISSUE TITLE
Ability to offset HMD pitch

### ISSUE THREAD

**Issue by cran1um** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#439]
I have a couple of separate use cases (I can elaborate further if needed) where it would be very useful to be able to adjust the HMD pitch so that the game environment believes the player is vertical/upright, when they are actually reclined (forward or backward)

I would like the ability to adjust the HMD pitch offset (without locking it at a fixed value) so that further pitch changes are relative to the starting offset (vs 0 offset standing upright)

**Comment by username223** [comment]
This would not be possible without writing a driver, which is outside the scope of this project.

I'm not sure if it's still maintained, but the [OpenVR Input Emulator](https://github.com/matzman666/OpenVR-InputEmulator) project could do this. You would likely have to find a fork of the original project, since I don't think Matzman666 is actively developing anything any more.

**Comment by cran1um** [comment]
thanks for the tip
