### ISSUE TITLE
Update Overlay to update dashboard resolution as well.

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#479]
https://github.com/elvissteinjr/SteamVR-ForceCompositorScale
`supersampleScaleCompositor` - appears to be an un-documented key to adjust the compositor resolution. calling setFloat on up to 1.5 should work?

Need to look into, but worth testing, for a marginally better experience.

**Comment by elvissteinjr** [comment]
I'm late to see this, but sorry to disappoint: 
That's not a secret key, it's just one made up by that crude app (as hinted in the code). I chose that route since the original key that used to exist to control the compositor/dashboard resolution is automatically deleted if it ever exists in the steamvr.vrsettings file. Perhaps I should've created a new settings section for it instead, but there wasn't a lot of time spent on planning for that tool and the functionality for a custom override was only quickly added since someone requested it.

I have not checked the current state of SteamVR, but if nothing changed, overwriting the gpuSpeed keys seems like the only way to get a higher compositor resolution besides getting a faster GPU. This may even have side-effects if some app tries to be smart and do something with those values, but not sure if any actually does. Still not my most favorite decision by the SteamVR devs.

**Comment by ykeara** [comment]
Yea, Well I think it's become a semi-official key I know at least one other overlay person using it now so It's the official un-official method XD.

**Comment by ykeara** [comment]
Going to cancel this, unfortunately It can lead to some other problematic issues, maybe worth a re-visit in the future, but for OVRAS it's not  really a great idea.
