### ISSUE TITLE
Playspace Moves Away From Me

### ISSUE THREAD

**Issue by neoaptt** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#488]
**Describe the bug**
Today july 9th when I use playspace, my playspace moves away from me. 

There was a steam vr update today "SteamVR 1.13 makes it convenient to re-center and re-orient your play area across all games. Check out the new button in the dashboard and try it for yourself."

**To Reproduce**
1. Use playspace mover

**Expected behavior**
I expect it to work like it's always has. If i enable the old "use frame update playspace mover setting" it works as expected but is very unoptimized and lags.

**Screenshots**
![test bug (2)](https://user-images.githubusercontent.com/9214528/87110439-44606280-c224-11ea-81dc-b20df43fead3.gif)

**Software (please complete the following information):**
 - OS: Windows 10
 - Advanced Settings Version: Tried both 4.0.1 and 5.2

**Hardware (please complete the following information):**
 - CPU: i9-9900k
 - Graphics Card: 2080ti RTX 
 - HMD: Vive Pro

**Additional context**
I restarted my computer, reinstalled 2 version of advanced settings, and re-settup my room settings. I'll look into reverting the steamvr version to see if this fixes it. If it does i'll let you know.

**Comment by ykeara** [comment]
Right SVR updated to 1.13 today, it broke things (or more technically SVR now behaves as documented), the easiest short fix is in the

`offsets tab` - un-check `adjust chaperone` This should fix it.

Will have a little more polished update in the next 24-72-ish hours, but https://ci.appveyor.com/project/OVRAdvancedSettings/openvr-advancedsettings/builds/33469222/job/34c46lbn170x27jn/artifacts the build here is what is live on steam, [if you just un-check adjust chaperone this will kill the center marker for now. that is fixed in this build] sorry for the confusion, new it was coming up Just Wasn't on top of it when it actually dropped : /
