### ISSUE TITLE
Allow Actions to be bound via key-bind

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#509]
As not all people in VR use tracked controllers we could add key-binding for keyboard keys allowing things like flight sims to use our existing actions without extremely specialized setups.

**Comment by donoli1st** [comment]
Hi have you done some research into your request? Would it be posible to do somthing? I would support you, if my capabilities alows it.. my goal would be to bind, in the best scenario, a joystick button to the menu button of the index controller. When you press the joybutton the passthrough camera will be activated.. you think this will be achievable? I hope you see this..

**Comment by ykeara** [comment]
For Our App, and it's actions it's certainly feasible, and really just another conditional on where we process our actions (overlaycontroller.cpp) [processx() functions]

The only real "hard" part is having the Polling/callbacks for input setup

**Comment by FredZvt** [comment]
Hi! I was looking here if there was someone asking for exactly this feature.

As an example of a use case, I refer to this thread: https://forum.il2sturmovik.com/topic/45974-exorcist-snap-view-in-vr/page/3/
Its a problem been around since 2019. OVRAS is being used as a way to snap turn inside the cockpit on the flight simulator but there are two caveats:

1. As @ykeara said, we don't use tracked controllers while piloting. Most of the flight sim pilots use some kind of controllers, most probably a HOTAS like this: http://www.thrustmaster.com/pt_BR/products/t16000m-fcs-flight-pack. So, ideallywe would like to map one of the buttons of a joystick or throttle controllers to snap turn left/right.

2. When snap turning left/right, the tracking area is rotated around the HMD location on the floor plane, not by the tracking area center. So after snapping back and forth, the center position is moved around and the head of the pilot is not where it way anymore. So, if we could add an option to snap turn around the HMD or around the center of the tracking area, it would be awesome.

I'm a programmer myself, but not that experienced in C++. If you show me the way, I can probably submit a PR with there changes.

**Comment by ykeara** [comment]
Closing this out, unfortunately this really needs to be it's own device driver, as such not really feasible from OVRAS end.
