### ISSUE TITLE
OVR is causing error 203 with Valve Index

### ISSUE THREAD

**Issue by Intoxicus** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#537]
Had to delete all SteamVR config files and then realized it was some conflict with OVR.
Would guess OVR and SteamVR are fighting over the same setting perhaps?
I causes SteamVR to crash the HMD and report a "SteamVR Fail" with error -203

**Comment by ykeara** [comment]
So we don't touch drivers at all, I would guess you kind of have an odd setup? and we have a race condition loading the third parties driver before we start.

would be interested more in what your setup is, but Sounds like there is a good chance this might be on Valve's end

**Comment by ykeara** [comment]
Without more information and not rep-produce-able closing out issue

**Comment by AdalynBlack** [comment]
Hi, I've been having the same issue recently, and I saw some reports that it might be related to OVR Advanced Settings, which tracks with when I started getting the error. Whenever I launch OVRAS, it's fine at first but after about 2-3 minutes, SteamVR completely crashes. I get SteamVR Fail (-203) and Headset Error (-202) right around the time that SteamVR breaks. It only happens when I touch OVRAS while using ALVR on Linux

I'm not sure if this is helpful or not, but these are all of the logs from my Steam logs directory: [SteamVRCrashLogs.tar.gz](https://github.com/user-attachments/files/16008924/SteamVRCrashLogs.tar.gz)
I couldn't find any ALVR specific logs in ~/.config like the README seemed to suggest, but if you know where they'd be located, I'd be happy to provide those logs as well
