### ISSUE TITLE
How to send updated coordinates back to openvr to change play area orientation/rotation?

### ISSUE THREAD

**Issue by RensTillmann** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#548]
Thanks for this plugin, it's really a masterpiece 👍 and helped me a lot to understand OpenVR better.

I am trying to create a simple program that turns the play space / play area around while in real life you keep facing the same direction. I found that the **Rotate Space** setting is exactly what I need: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#--space-offset-page

As per my understanding the magic seems to be happening here: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/3ab10ce334c29be55533be1168c490dc6539f10a/src/tabcontrollers/MoveCenterTabController.cpp#L319

I have been trying to reproduce this on my end, but can't get it to work. Obviously I am doing something wrong, or missing something. Now my question is as follows:

On the OpenVR wiki it states that you require Qt5 for it to work. I simply can't get this Qt5 thing to work on my end so I gave up on that. I thought it wasn't required anyway as long as you don't need to create UI interface (but perhaps I am wrong).

I currently have the following code, which simply prints out the quaternion representation, but I just need to understand how I can pass through edited values, so for instance that for the Y axis I can add an additional "45" degrees as an example.

I am kinda stuck now, hence I am asking for help here. Meanwhile I will try to do some more testing/research.

```
		// Get hmd pose matrix.
		vr::TrackedDevicePose_t devicePosesForRot[vr::k_unMaxTrackedDeviceCount];
		int m_trackingUniverse = static_cast<int>( vr::TrackingUniverseStanding );
		if ( m_trackingUniverse == vr::TrackingUniverseSeated ) {
			vr::VRSystem()->GetDeviceToAbsoluteTrackingPose( vr::TrackingUniverseSeated, 0.0f, devicePosesForRot, vr::k_unMaxTrackedDeviceCount );
		} else {
			vr::VRSystem()->GetDeviceToAbsoluteTrackingPose( vr::TrackingUniverseStanding, 0.0f, devicePosesForRot, vr::k_unMaxTrackedDeviceCount );
		}
		// Quaternion representing rotation
		vr::HmdMatrix34_t matrix = devicePosesForRot[0].mDeviceToAbsoluteTracking;
		vr::HmdQuaternion_t q;
		q.w = sqrt(fmax(0, 1 + matrix.m[0][0] + matrix.m[1][1] + matrix.m[2][2])) / 2;
		q.x = sqrt(fmax(0, 1 + matrix.m[0][0] - matrix.m[1][1] - matrix.m[2][2])) / 2;
		q.y = sqrt(fmax(0, 1 - matrix.m[0][0] + matrix.m[1][1] - matrix.m[2][2])) / 2;
		q.z = sqrt(fmax(0, 1 - matrix.m[0][0] - matrix.m[1][1] + matrix.m[2][2])) / 2;
		q.x = copysign(q.x, matrix.m[2][1] - matrix.m[1][2]);
		q.y = copysign(q.y, matrix.m[0][2] - matrix.m[2][0]);
		q.z = copysign(q.z, matrix.m[1][0] - matrix.m[0][1]);
		sprintf_s(buf, sizeof(buf), "qw: %.2f qx: %.2f qy: %.2f qz: %.2f\n", q.w, q.x, q.y, q.z);
		printf_s(buf);

		float offsetY = 0.5; // some change in Y axis value
                q.y = q.z + offsetY; // << just an example, to change rotation
                // Now what to do, need to send updated value to openvr somehow... so the updated value reflects rotation in game
                // ...
```

Which prints out this as an example:

`qw: 0.55 qx: 0.06 qy: -0.83 qz: 0.11`

**Comment by Kung-vr** [comment]
Greetings! So if you're building your own fork of OVRAS all that is needed is to call MoveCenterTabController::setRotation() from somewhere to set whatever rotation you want. This value is an int in centidegrees (for example 9000 is 90 degrees). I could ramble about why it's that way but it's not really relevant here. This is the rotation "offset" from the current saved-on-disk openvr universe center orientation. In the MoveCenterTabController::updateSpace() function which is called on our event loop ticks, m_rotation will be picked up and the openvr universe center will be set to that offset rotation. Calling  emit rotationChanged( m_rotation ) is only needed for the QML UI to pick up the changed rotation.

So that's if you're building a fork, if you're doing your own project from scratch though you'll have a lot of work ahead to reproduce OVRAS's HMD centered rotation behavior.

If instead universe centered rotation is good enough for your project, then it's not too hard and you can work with a simple app that applies a rotational offset. You can see what this is like in vr by enabling Universe-Centered Rotation in the OVRAS settings tab. If that kind of rotation works for you, you can see the how we update the universe center:

It's acquired from openvr here:
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/3ab10ce334c29be55533be1168c490dc6539f10a/src/tabcontrollers/MoveCenterTabController.cpp#L1249

Multiplied by a rotation matrix here:
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/3ab10ce334c29be55533be1168c490dc6539f10a/src/tabcontrollers/MoveCenterTabController.cpp#L2601

It's sent back to openvr here:
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/3ab10ce334c29be55533be1168c490dc6539f10a/src/tabcontrollers/MoveCenterTabController.cpp#L2840

And this causes it to actually update the vr session to use the new center:
https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/3ab10ce334c29be55533be1168c490dc6539f10a/src/tabcontrollers/MoveCenterTabController.cpp#L2897

If you want the rotation to by applied at the location of the hmd (such that the vr world seems rotate around the player) that's a whole lot of extra work... you'll also need to build in positional offset support, and probably support to reset those offsets. This is because as we rotate in head-centered mode we calculate the necessary X,Z offsets to cancel the apparent shift in the player's position as they sweep across the arc of rotation around the universe center and apply this offset to universe center's position to compensate. Also if you're supporting offsets and rotation you'll need to build your app keeping in mind that the raw center and the standing/seated center will likely not be X/Z axis aligned, so you'll need to unrotate your coordinates where appropriate when calculating arc offsets, etc... Most of the arc offset calculation is in setRotation() and then the handling of both rotation and offset to the universe center is mostly in updateSpace(). If HMD centered rotation is required for you, in my opinion it'd probably be easier to get Qt working and build this into an OVRAS fork that just calls setRotation(), because otherwise a lot of your work would be in reinventing the wheel we have set up in OVRAS for handling this non-native hmd centered rotation (and resulting requirements for a positional offset system).

**Comment by RensTillmann** [comment]
@Kung-vr Hi, and thanks for the detailed explanation, this is really helpful! At first I wasn't planning on building from a fork, but based on your explanation this might be the easiest and best way to go with for now. In the meantime I was able to get Qt5 up and running, sot that's out the way now. I will now first try to call the setRotation() and see how that plays out for my usecase.

And thanks again for your detailed explanation 👍  I will close this "issue" for now, have a great day!
