### ISSUE TITLE
Playspace speed

### ISSUE THREAD

**Issue by TARDIS76** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#589]
Please make it so you can move faster or slower when you move your avatar around while standing still or laying down. I love laying in my bed playing VR and sometimes I need to move my small avatar up or down but it takes forever because it's so slow. Please make it so you can adjust the speed of the movement like you can with a gamjng mouse. I'm sure other people would love this as well.

**Comment by ViniciusFXavier** [comment]
This can be a little tricky, because depending on the game it can be detected as a cheat, and if the person changes it, they can end up being banned.

Rotation and even gravity I believe is easier than accelerating.

---

It is possible to increase the speed by increasing the offset but it is dangerous you start to fall off the map.

---
- **VR Chat**
  - No mods:
    - In VRChat the speed at which the character walks is added to the character at the time of creation so if you create characters it is possible to make this change through Unity before exporting. If you use already created characters you are dependent on the character settings.

  - With Mods:
    # **Attention: There is a chance you may have your account permanently banned for using mods in the game.**

    Assuming you're playing VRChat, there's a MOD that helps you increase your speed.

    How to install MODS in VRChat:
    https://www.youtube.com/watch?v=YFbvifyFzKs

    In VRMelonAssistant it is one of the first two mods It allows you to run super fast, fly, interact with other avatars or even allow them to interact with yours.
    Just remember, your account may be get banned.
---

Other games like Fallout 4 or Skyrim have options in the game settings that allow you to make these adjustments.

---

Games like REC ROOM, **do not use the OVR Toolkit high chance of being banned** even if it is using the steam interface under the hood.

The Game has an anti-cheat, and even applications like virtual desktop can get you banned.

**Comment by ViniciusFXavier** [comment]
Update:
For now you can try to decrease gravity, this decreases friction and allows you to walk faster, and go faster and faster.

**Comment by ykeara** [comment]
There is a drag Multiplier in space Drag now, that should effectively do this if I'm understanding issue correctly.
