### ISSUE TITLE
Open vr ne s'ouvre pas 

### ISSUE THREAD

**Issue by Machlas86** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#619]
Bonjour mon problème concerne open vr advanced
Je viens de supprimer steamvr de steam puis installé open vr advanced le problème c est que rien ne s'ouvre quand je lance open vr merci

**Comment by ykeara** [comment]
Hey thank you for your ticket unfortunately we really aren't able to help in languages aside from english.


Google translate of your ticket:

Hello my problem concerns open vr advanced
I just removed steamvr from steam then installed open vr advanced the problem is that nothing opens when I launch open vr thank you




I think that is as expected, we do not replace steamvr, and as such it will be required to use ovras. other than that if that is not your issue need more information.
