### ISSUE TITLE
OVR Advanced Settings changing to be paid

### ISSUE THREAD

**Issue by Kamilake** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#666]
https://store.steampowered.com/news/app/1009850/view/4186732260747183901

![image](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/assets/15166740/91c4b44c-11df-4a0a-82ef-10a95b5b0bc5)

I've heard that OVRAS is going to be paid on Steam.

That's certainly worth it, but I don't see anything related to this repository. 

Will the monetization that happened on Steam also affect this repository, e.g. will it be modified so that it's no longer open source, can't be contributed to, or can't be built on?

Or will everything remain as it is now?

Thanks to everyone who has contributed to this repository!

**Comment by ykeara** [comment]
First and foremost, I can't really mention the repo on Steam due to contractual obligations with valve.

Secondly yes especially after the change I am incentivized to not really point to this repo.

The Intent is to continue things with the current status quo. I.e. yes we are staying open-source, yes this repo will receive the same updates.

IT IS POSSIBLE that I will have to remove binaries, either from future updates or from all releases

**Comment by e00E** [comment]
Could you explain the following more?
- > I can't really mention the repo on Steam due to contractual obligations with valve.
- > IT IS POSSIBLE that I will have to remove binaries

Why is that the case? I understand why you might want to do this but I don't understand why you'd be forced to by Steam.

**Comment by Kamilake** [comment]
> Could you explain the following more?

Same opinion; They seem to have some kind of non-disclosure agreement with valve.
I understand that not all open source software is free. But they had to explain more detailed reasons.

**Comment by Kamilake** [comment]
* > IT IS POSSIBLE that I will have to remove binaries

Removing binaries from releases isn't really a big deal. Anyone can create automatic build, automatic update tools
